package rholang.parsing.lambda.Absyn; // Java Package generated by the BNF Converter.

public abstract class TType implements java.io.Serializable {
  public abstract <R,A> R accept(TType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rholang.parsing.lambda.Absyn.TType2 p, A arg);
    public R visit(rholang.parsing.lambda.Absyn.TType3 p, A arg);

  }

}
