package rholang.parsing.lambda.Absyn; // Java Package generated by the BNF Converter.

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rholang.parsing.lambda.Absyn.TSimple p, A arg);
    public R visit(rholang.parsing.lambda.Absyn.TTuple p, A arg);
    public R visit(rholang.parsing.lambda.Absyn.TFun p, A arg);

  }

}
