package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public abstract class Bind implements java.io.Serializable {
  public abstract <R,A> R accept(Bind.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.syntax.rholang.Absyn.InputBind p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.CondInputBind p, A arg);

  }

}
