package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class CPtQuote extends CPattern {
  public final PPattern ppattern_;
  public CPtQuote(PPattern p1) { ppattern_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.CPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.CPtQuote) {
      coop.rchain.syntax.rholang.Absyn.CPtQuote x = (coop.rchain.syntax.rholang.Absyn.CPtQuote)o;
      return this.ppattern_.equals(x.ppattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.ppattern_.hashCode();
  }


}
