package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class CPtVar extends CPattern {
  public final VarPattern varpattern_;
  public CPtVar(VarPattern p1) { varpattern_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.CPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.CPtVar) {
      coop.rchain.syntax.rholang.Absyn.CPtVar x = (coop.rchain.syntax.rholang.Absyn.CPtVar)o;
      return this.varpattern_.equals(x.varpattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.varpattern_.hashCode();
  }


}
