package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class CQuote extends Chan {
  public final Proc proc_;
  public CQuote(Proc p1) { proc_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.Chan.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.CQuote) {
      coop.rchain.syntax.rholang.Absyn.CQuote x = (coop.rchain.syntax.rholang.Absyn.CQuote)o;
      return this.proc_.equals(x.proc_);
    }
    return false;
  }

  public int hashCode() {
    return this.proc_.hashCode();
  }


}
