package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class PChoice extends Proc {
  public final ListCBranch listcbranch_;
  public PChoice(ListCBranch p1) { listcbranch_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.Proc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.PChoice) {
      coop.rchain.syntax.rholang.Absyn.PChoice x = (coop.rchain.syntax.rholang.Absyn.PChoice)o;
      return this.listcbranch_.equals(x.listcbranch_);
    }
    return false;
  }

  public int hashCode() {
    return this.listcbranch_.hashCode();
  }


}
