package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class PConstr extends Proc {
  public final String name_;
  public final ListProc listproc_;
  public PConstr(String p1, ListProc p2) { name_ = p1; listproc_ = p2; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.Proc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.PConstr) {
      coop.rchain.syntax.rholang.Absyn.PConstr x = (coop.rchain.syntax.rholang.Absyn.PConstr)o;
      return this.name_.equals(x.name_) && this.listproc_.equals(x.listproc_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.name_.hashCode())+this.listproc_.hashCode();
  }


}
