package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class PPtConstr extends PPattern {
  public final String var_;
  public final ListPPattern listppattern_;
  public PPtConstr(String p1, ListPPattern p2) { var_ = p1; listppattern_ = p2; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.PPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.PPtConstr) {
      coop.rchain.syntax.rholang.Absyn.PPtConstr x = (coop.rchain.syntax.rholang.Absyn.PPtConstr)o;
      return this.var_.equals(x.var_) && this.listppattern_.equals(x.listppattern_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.var_.hashCode())+this.listppattern_.hashCode();
  }


}
