package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class PPtVal extends PPattern {
  public final ValPattern valpattern_;
  public PPtVal(ValPattern p1) { valpattern_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.PPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.PPtVal) {
      coop.rchain.syntax.rholang.Absyn.PPtVal x = (coop.rchain.syntax.rholang.Absyn.PPtVal)o;
      return this.valpattern_.equals(x.valpattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.valpattern_.hashCode();
  }


}
