package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class PtBind extends PatternBind {
  public final CPattern cpattern_1, cpattern_2;
  public PtBind(CPattern p1, CPattern p2) { cpattern_1 = p1; cpattern_2 = p2; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.PatternBind.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.PtBind) {
      coop.rchain.syntax.rholang.Absyn.PtBind x = (coop.rchain.syntax.rholang.Absyn.PtBind)o;
      return this.cpattern_1.equals(x.cpattern_1) && this.cpattern_2.equals(x.cpattern_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.cpattern_1.hashCode())+this.cpattern_2.hashCode();
  }


}
