package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class PValue extends Proc {
  public final Value value_;
  public PValue(Value p1) { value_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.Proc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.PValue) {
      coop.rchain.syntax.rholang.Absyn.PValue x = (coop.rchain.syntax.rholang.Absyn.PValue)o;
      return this.value_.equals(x.value_);
    }
    return false;
  }

  public int hashCode() {
    return this.value_.hashCode();
  }


}
