package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class QBool extends Quantity {
  public final RhoBool rhobool_;
  public QBool(RhoBool p1) { rhobool_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.Quantity.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.QBool) {
      coop.rchain.syntax.rholang.Absyn.QBool x = (coop.rchain.syntax.rholang.Absyn.QBool)o;
      return this.rhobool_.equals(x.rhobool_);
    }
    return false;
  }

  public int hashCode() {
    return this.rhobool_.hashCode();
  }


}
