package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class QMult extends Quantity {
  public final Quantity quantity_1, quantity_2;
  public QMult(Quantity p1, Quantity p2) { quantity_1 = p1; quantity_2 = p2; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.Quantity.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.QMult) {
      coop.rchain.syntax.rholang.Absyn.QMult x = (coop.rchain.syntax.rholang.Absyn.QMult)o;
      return this.quantity_1.equals(x.quantity_1) && this.quantity_2.equals(x.quantity_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.quantity_1.hashCode())+this.quantity_2.hashCode();
  }


}
