package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class QString extends Quantity {
  public final String string_;
  public QString(String p1) { string_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.Quantity.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.QString) {
      coop.rchain.syntax.rholang.Absyn.QString x = (coop.rchain.syntax.rholang.Absyn.QString)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
