package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public abstract class Quantity implements java.io.Serializable {
  public abstract <R,A> R accept(Quantity.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.syntax.rholang.Absyn.QBool p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QInt p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QDouble p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QString p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QVar p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QDot p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QNeg p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QMult p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QDiv p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QAdd p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QMinus p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QLt p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QLte p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QGt p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QGte p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QEq p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QNeq p, A arg);

  }

}
