package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public abstract class RhoBool implements java.io.Serializable {
  public abstract <R,A> R accept(RhoBool.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.syntax.rholang.Absyn.QTrue p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.QFalse p, A arg);

  }

}
