package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public abstract class VarPattern implements java.io.Serializable {
  public abstract <R,A> R accept(VarPattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.syntax.rholang.Absyn.VarPtVar p, A arg);
    public R visit(coop.rchain.syntax.rholang.Absyn.VarPtWild p, A arg);

  }

}
