package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class VarPtVar extends VarPattern {
  public final String var_;
  public VarPtVar(String p1) { var_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.VarPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.VarPtVar) {
      coop.rchain.syntax.rholang.Absyn.VarPtVar x = (coop.rchain.syntax.rholang.Absyn.VarPtVar)o;
      return this.var_.equals(x.var_);
    }
    return false;
  }

  public int hashCode() {
    return this.var_.hashCode();
  }


}
