package coop.rchain.syntax.rholang.Absyn; // Java Package generated by the BNF Converter.

public class VPtInt extends ValPattern {
  public final Integer integer_;
  public VPtInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(coop.rchain.syntax.rholang.Absyn.ValPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.syntax.rholang.Absyn.VPtInt) {
      coop.rchain.syntax.rholang.Absyn.VPtInt x = (coop.rchain.syntax.rholang.Absyn.VPtInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
