branches:
  - dev
  - master
  - release-*
  - testing*

# Common parts

# FYI: There's no merging of arrays in YAML. At least not in the Go library
# Drone uses to parse YAML. So if you mix in &sbtenv and want to add
# additional volumes, as in package step, you need to specify all volumes.

__buildenv: &buildenv
  image: rchain/buildenv:latest

__sbtenv: &sbtenv
  <<: *buildenv
  environment:
    - _JAVA_OPTIONS=-Xms2G -Xmx4G -XX:MaxMetaspaceSize=1G
  volumes:
    - /var/cache/rchain-build/.sbt:/root/.sbt
    - /var/cache/rchain-build/.ivy2:/root/.ivy2

# Build definition

clone:
  git-clone:
    image: rchain/buildenv:latest
    commands: |
      set -ex
      git clone -b ${DRONE_TAG:-$DRONE_BRANCH} $DRONE_REMOTE_URL .
      if [ x$DRONE_PULL_REQUEST != x ]; then
          git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
          EMAIL=ci git merge --no-edit FETCH_HEAD
      fi
      git rev-parse HEAD

pipeline:

  # pr

  sbt-update:
    <<: *sbtenv
    commands:
      - sbt update

  compile:
    <<: *sbtenv
    commands:
      - sbt rholang/bnfc:generate compile test:compile it:compile doc

  # push

  package:
    <<: *sbtenv
    commands:
      - sbt node/docker:publishLocal node/debian:packageBin node/universal:packageZipTarball
      - mkdir -p artifacts
      - cp node/target/rnode_*_all.deb node/target/universal/*.tgz artifacts/
    volumes:
      - /var/cache/rchain-build/.sbt:/root/.sbt
      - /var/cache/rchain-build/.ivy2:/root/.ivy2
      - /var/run/docker.sock:/var/run/docker.sock

  run-integration-tests:
    <<: *buildenv
    environment:
      - _JAVA_OPTIONS=-Xms2G -Xmx4G
    commands:
      - ./scripts/ci/run-integration-tests.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - /var/tmp/rchain-it:/var/tmp/rchain-it

  package-rpm:
    <<: *sbtenv
    commands:
      - env JAVAC_VERSION=1.8 sbt clean compile doc node/rpm:packageBin
      - mkdir -p artifacts
      - cp node/target/rpm/RPMS/noarch/rnode-*.noarch.rpm artifacts/
    volumes:
      - /var/cache/rchain-build/.sbt:/root/.sbt
      - /var/cache/rchain-build/.ivy2:/root/.ivy2
    when:
      event: [ push, tag ]

  publish:
    <<: *buildenv
    commands:
      - ./scripts/ci/publish-artifacts
    secrets:
      - docker_username
      - docker_password
      - ssh_private_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [ push, tag ]

  notify:
    <<: *buildenv
    commands:
      - ./scripts/ci/send-email
    secrets:
      - email_host
      - email_username
      - email_password
      - email_recipients
      - email_sender
    when:
      event: [ push, tag ]
      status: [ changed, failure ]
