/* automatically generated by pepy 7.0 #14 (nanook.mcc.com), do not edit! */

#include "psap.h"

#define	advise	PY_advise

void	advise ();

/* Generated from module IMISC */

#include <stdio.h>
#include "IMISC-types.h"

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	decode_IMISC_TimeResult (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
struct type_IMISC_TimeResult ** parm;
{
    register integer p5;

#ifdef DEBUG
    (void) testdebug (pe, "IMISC.TimeResult");
#endif

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "TimeResult bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "TimeResult bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    {
# line 62 "IMISC-types.py"

        if ((*(parm) = (struct type_IMISC_TimeResult *)
                calloc (1, sizeof **(parm))) == ((struct type_IMISC_TimeResult *) 0)) {
            advise (NULLCP, "%s", PEPY_ERR_NOMEM);
            return NOTOK;
        }
    
    }
    if ((p5 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "TimeResult %s%s", PEPY_ERR_BAD_INTEGER,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    (*parm) -> parm  = p5;
    if (len)
        *len = p5;

    return OK;
}
