/* automatically generated by pepy 7.0 #14 (nanook.mcc.com), do not edit! */

#include "psap.h"

#define	advise	PY_advise

void	advise ();

/* Generated from module IMISC */

#include <stdio.h>
#include "IMISC-types.h"

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	encode_IMISC_IA5List (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
struct type_IMISC_IA5List * parm;
{
    PE	p0 = NULLPE;
    PE	p1_z = NULLPE;
    register PE *p1 = &p1_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SEQ)) == NULLPE) {
        advise (NULLCP, "IA5List: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }
    for (; parm; parm = parm -> next) {
        if (encode_UNIV_IA5String (p1, 0, NULL, NULLCP, parm -> IA5String ) == NOTOK)
            return NOTOK;

#ifdef DEBUG
        (void) testdebug ((*p1), "element");
#endif

        seq_addon ((*pe), p0, (*p1));
        p0 = (*p1);
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "IMISC.IA5List");
#endif


    return OK;
}
