/* automatically generated by rosy 7.0 #14 (nanook.mcc.com), do not edit! */

#include "rosy.h"


					/* OPERATIONS */

extern struct RyOperation table_IMISC_Operations[];

					/* OPERATION utcTime */
#define operation_IMISC_utcTime	0

#ifdef	INVOKER
#define	encode_IMISC_utcTime_argument	NULLIFP
#define	decode_IMISC_utcTime_result	decode_IMISC_UTCResult
#define	free_IMISC_utcTime_result	free_IMISC_UTCResult
#else
#define	encode_IMISC_utcTime_argument	NULLIFP
#define	decode_IMISC_utcTime_result	NULLIFP
#define	free_IMISC_utcTime_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_utcTime_argument	NULLIFP
#define	free_IMISC_utcTime_argument	NULLIFP
#define	encode_IMISC_utcTime_result	encode_IMISC_UTCResult
#else
#define	decode_IMISC_utcTime_argument	NULLIFP
#define	free_IMISC_utcTime_argument	NULLIFP
#define	encode_IMISC_utcTime_result	NULLIFP
#endif

					/* OPERATION timeOfDay */
#define operation_IMISC_timeOfDay	1

#ifdef	INVOKER
#define	encode_IMISC_timeOfDay_argument	NULLIFP
#define	decode_IMISC_timeOfDay_result	decode_IMISC_TimeResult
#define	free_IMISC_timeOfDay_result	free_IMISC_TimeResult
#else
#define	encode_IMISC_timeOfDay_argument	NULLIFP
#define	decode_IMISC_timeOfDay_result	NULLIFP
#define	free_IMISC_timeOfDay_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_timeOfDay_argument	NULLIFP
#define	free_IMISC_timeOfDay_argument	NULLIFP
#define	encode_IMISC_timeOfDay_result	encode_IMISC_TimeResult
#else
#define	decode_IMISC_timeOfDay_argument	NULLIFP
#define	free_IMISC_timeOfDay_argument	NULLIFP
#define	encode_IMISC_timeOfDay_result	NULLIFP
#endif

					/* OPERATION users */
#define operation_IMISC_users	2

#ifdef	INVOKER
#define	encode_IMISC_users_argument	NULLIFP
#define	decode_IMISC_users_result	decode_IMISC_IA5List
#define	free_IMISC_users_result	free_IMISC_IA5List
#else
#define	encode_IMISC_users_argument	NULLIFP
#define	decode_IMISC_users_result	NULLIFP
#define	free_IMISC_users_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_users_argument	NULLIFP
#define	free_IMISC_users_argument	NULLIFP
#define	encode_IMISC_users_result	encode_IMISC_IA5List
#else
#define	decode_IMISC_users_argument	NULLIFP
#define	free_IMISC_users_argument	NULLIFP
#define	encode_IMISC_users_result	NULLIFP
#endif

					/* OPERATION charGen */
#define operation_IMISC_charGen	3

#ifdef	INVOKER
#define	encode_IMISC_charGen_argument	NULLIFP
#define	decode_IMISC_charGen_result	decode_IMISC_IA5List
#define	free_IMISC_charGen_result	free_IMISC_IA5List
#else
#define	encode_IMISC_charGen_argument	NULLIFP
#define	decode_IMISC_charGen_result	NULLIFP
#define	free_IMISC_charGen_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_charGen_argument	NULLIFP
#define	free_IMISC_charGen_argument	NULLIFP
#define	encode_IMISC_charGen_result	encode_IMISC_IA5List
#else
#define	decode_IMISC_charGen_argument	NULLIFP
#define	free_IMISC_charGen_argument	NULLIFP
#define	encode_IMISC_charGen_result	NULLIFP
#endif

					/* OPERATION qotd */
#define operation_IMISC_qotd	4

#ifdef	INVOKER
#define	encode_IMISC_qotd_argument	NULLIFP
#define	decode_IMISC_qotd_result	decode_IMISC_IA5List
#define	free_IMISC_qotd_result	free_IMISC_IA5List
#else
#define	encode_IMISC_qotd_argument	NULLIFP
#define	decode_IMISC_qotd_result	NULLIFP
#define	free_IMISC_qotd_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_qotd_argument	NULLIFP
#define	free_IMISC_qotd_argument	NULLIFP
#define	encode_IMISC_qotd_result	encode_IMISC_IA5List
#else
#define	decode_IMISC_qotd_argument	NULLIFP
#define	free_IMISC_qotd_argument	NULLIFP
#define	encode_IMISC_qotd_result	NULLIFP
#endif

					/* OPERATION finger */
#define operation_IMISC_finger	5

#ifdef	INVOKER
#define	encode_IMISC_finger_argument	encode_IMISC_IA5List
#define	decode_IMISC_finger_result	decode_IMISC_IA5List
#define	free_IMISC_finger_result	free_IMISC_IA5List
#else
#define	encode_IMISC_finger_argument	NULLIFP
#define	decode_IMISC_finger_result	NULLIFP
#define	free_IMISC_finger_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_finger_argument	decode_IMISC_IA5List
#define	free_IMISC_finger_argument	free_IMISC_IA5List
#define	encode_IMISC_finger_result	encode_IMISC_IA5List
#else
#define	decode_IMISC_finger_argument	NULLIFP
#define	free_IMISC_finger_argument	NULLIFP
#define	encode_IMISC_finger_result	NULLIFP
#endif

					/* OPERATION pwdGen */
#define operation_IMISC_pwdGen	6

#ifdef	INVOKER
#define	encode_IMISC_pwdGen_argument	NULLIFP
#define	decode_IMISC_pwdGen_result	decode_IMISC_IA5List
#define	free_IMISC_pwdGen_result	free_IMISC_IA5List
#else
#define	encode_IMISC_pwdGen_argument	NULLIFP
#define	decode_IMISC_pwdGen_result	NULLIFP
#define	free_IMISC_pwdGen_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_pwdGen_argument	NULLIFP
#define	free_IMISC_pwdGen_argument	NULLIFP
#define	encode_IMISC_pwdGen_result	encode_IMISC_IA5List
#else
#define	decode_IMISC_pwdGen_argument	NULLIFP
#define	free_IMISC_pwdGen_argument	NULLIFP
#define	encode_IMISC_pwdGen_result	NULLIFP
#endif

					/* OPERATION genTime */
#define operation_IMISC_genTime	7

#ifdef	INVOKER
#define	encode_IMISC_genTime_argument	NULLIFP
#define	decode_IMISC_genTime_result	decode_IMISC_GenResult
#define	free_IMISC_genTime_result	free_IMISC_GenResult
#else
#define	encode_IMISC_genTime_argument	NULLIFP
#define	decode_IMISC_genTime_result	NULLIFP
#define	free_IMISC_genTime_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_genTime_argument	NULLIFP
#define	free_IMISC_genTime_argument	NULLIFP
#define	encode_IMISC_genTime_result	encode_IMISC_GenResult
#else
#define	decode_IMISC_genTime_argument	NULLIFP
#define	free_IMISC_genTime_argument	NULLIFP
#define	encode_IMISC_genTime_result	NULLIFP
#endif

					/* OPERATION tellUser */
#define operation_IMISC_tellUser	8

#ifdef	INVOKER
#define	encode_IMISC_tellUser_argument	encode_IMISC_IA5List
#define	decode_IMISC_tellUser_result	decode_IMISC_Empty
#define	free_IMISC_tellUser_result	free_IMISC_Empty
#else
#define	encode_IMISC_tellUser_argument	NULLIFP
#define	decode_IMISC_tellUser_result	NULLIFP
#define	free_IMISC_tellUser_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_tellUser_argument	decode_IMISC_IA5List
#define	free_IMISC_tellUser_argument	free_IMISC_IA5List
#define	encode_IMISC_tellUser_result	encode_IMISC_Empty
#else
#define	decode_IMISC_tellUser_argument	NULLIFP
#define	free_IMISC_tellUser_argument	NULLIFP
#define	encode_IMISC_tellUser_result	NULLIFP
#endif

					/* OPERATION ping */
#define operation_IMISC_ping	9

#ifdef	INVOKER
#define	encode_IMISC_ping_argument	encode_IMISC_Empty
#define	decode_IMISC_ping_result	decode_IMISC_Empty
#define	free_IMISC_ping_result	free_IMISC_Empty
#else
#define	encode_IMISC_ping_argument	NULLIFP
#define	decode_IMISC_ping_result	NULLIFP
#define	free_IMISC_ping_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_ping_argument	decode_IMISC_Empty
#define	free_IMISC_ping_argument	free_IMISC_Empty
#define	encode_IMISC_ping_result	encode_IMISC_Empty
#else
#define	decode_IMISC_ping_argument	NULLIFP
#define	free_IMISC_ping_argument	NULLIFP
#define	encode_IMISC_ping_result	NULLIFP
#endif

					/* OPERATION sink */
#define operation_IMISC_sink	10

#ifdef	INVOKER
#define	encode_IMISC_sink_argument	encode_IMISC_Data
#define	decode_IMISC_sink_result	decode_IMISC_Empty
#define	free_IMISC_sink_result	free_IMISC_Empty
#else
#define	encode_IMISC_sink_argument	NULLIFP
#define	decode_IMISC_sink_result	NULLIFP
#define	free_IMISC_sink_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_sink_argument	decode_IMISC_Data
#define	free_IMISC_sink_argument	free_IMISC_Data
#define	encode_IMISC_sink_result	encode_IMISC_Empty
#else
#define	decode_IMISC_sink_argument	NULLIFP
#define	free_IMISC_sink_argument	NULLIFP
#define	encode_IMISC_sink_result	NULLIFP
#endif

					/* OPERATION echo */
#define operation_IMISC_echo	11

#ifdef	INVOKER
#define	encode_IMISC_echo_argument	encode_IMISC_Data
#define	decode_IMISC_echo_result	decode_IMISC_Data
#define	free_IMISC_echo_result	free_IMISC_Data
#else
#define	encode_IMISC_echo_argument	NULLIFP
#define	decode_IMISC_echo_result	NULLIFP
#define	free_IMISC_echo_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_IMISC_echo_argument	decode_IMISC_Data
#define	free_IMISC_echo_argument	free_IMISC_Data
#define	encode_IMISC_echo_result	encode_IMISC_Data
#else
#define	decode_IMISC_echo_argument	NULLIFP
#define	free_IMISC_echo_argument	NULLIFP
#define	encode_IMISC_echo_result	NULLIFP
#endif


#ifndef	lint

#define stub_IMISC_utcTime(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_utcTime, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_utcTime(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_utcTime,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_timeOfDay(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_timeOfDay, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_timeOfDay(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_timeOfDay,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_users(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_users, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_users(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_users,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_charGen(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_charGen, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_charGen(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_charGen,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_qotd(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_qotd, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_qotd(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_qotd,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_finger(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_finger, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_finger(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_finger,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_pwdGen(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_pwdGen, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_pwdGen(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_pwdGen,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_genTime(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_genTime, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_genTime(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_genTime,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_tellUser(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_tellUser, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_tellUser(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_tellUser,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_ping(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_ping, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_ping(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_ping,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_sink(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_sink, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_sink(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_sink,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_IMISC_echo(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_IMISC_Operations, operation_IMISC_echo, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_IMISC_echo(sd,in,out,rsp,roi)\
RyOperation ((sd), table_IMISC_Operations, operation_IMISC_echo,\
	(caddr_t) (in), (out), (rsp), (roi))
#endif


					/* ERRORS */

extern struct RyError table_IMISC_Errors[];

					/* ERROR congested */
#define error_IMISC_congested	0

#ifdef	INVOKER
#define	decode_IMISC_congested_parameter	NULLIFP
#define	free_IMISC_congested_parameter	NULLIFP
#else
#define	decode_IMISC_congested_parameter	NULLIFP
#define	free_IMISC_congested_parameter	NULLIFP
#endif

#ifdef	PERFORMER
#define	encode_IMISC_congested_parameter	NULLIFP
#else
#define	encode_IMISC_congested_parameter	NULLIFP
#endif


					/* ERROR unableToDetermineTime */
#define error_IMISC_unableToDetermineTime	1

#ifdef	INVOKER
#define	decode_IMISC_unableToDetermineTime_parameter	NULLIFP
#define	free_IMISC_unableToDetermineTime_parameter	NULLIFP
#else
#define	decode_IMISC_unableToDetermineTime_parameter	NULLIFP
#define	free_IMISC_unableToDetermineTime_parameter	NULLIFP
#endif

#ifdef	PERFORMER
#define	encode_IMISC_unableToDetermineTime_parameter	NULLIFP
#else
#define	encode_IMISC_unableToDetermineTime_parameter	NULLIFP
#endif


					/* ERROR unableToOpenFile */
#define error_IMISC_unableToOpenFile	2

#ifdef	INVOKER
#define	decode_IMISC_unableToOpenFile_parameter	decode_IMISC_IA5List
#define	free_IMISC_unableToOpenFile_parameter	free_IMISC_IA5List
#else
#define	decode_IMISC_unableToOpenFile_parameter	NULLIFP
#define	free_IMISC_unableToOpenFile_parameter	NULLIFP
#endif

#ifdef	PERFORMER
#define	encode_IMISC_unableToOpenFile_parameter	encode_IMISC_IA5List
#else
#define	encode_IMISC_unableToOpenFile_parameter	NULLIFP
#endif


					/* ERROR unableToAccessFile */
#define error_IMISC_unableToAccessFile	3

#ifdef	INVOKER
#define	decode_IMISC_unableToAccessFile_parameter	decode_IMISC_IA5List
#define	free_IMISC_unableToAccessFile_parameter	free_IMISC_IA5List
#else
#define	decode_IMISC_unableToAccessFile_parameter	NULLIFP
#define	free_IMISC_unableToAccessFile_parameter	NULLIFP
#endif

#ifdef	PERFORMER
#define	encode_IMISC_unableToAccessFile_parameter	encode_IMISC_IA5List
#else
#define	encode_IMISC_unableToAccessFile_parameter	NULLIFP
#endif


					/* ERROR unableToPipe */
#define error_IMISC_unableToPipe	4

#ifdef	INVOKER
#define	decode_IMISC_unableToPipe_parameter	decode_IMISC_IA5List
#define	free_IMISC_unableToPipe_parameter	free_IMISC_IA5List
#else
#define	decode_IMISC_unableToPipe_parameter	NULLIFP
#define	free_IMISC_unableToPipe_parameter	NULLIFP
#endif

#ifdef	PERFORMER
#define	encode_IMISC_unableToPipe_parameter	encode_IMISC_IA5List
#else
#define	encode_IMISC_unableToPipe_parameter	NULLIFP
#endif


					/* ERROR unableToFork */
#define error_IMISC_unableToFork	5

#ifdef	INVOKER
#define	decode_IMISC_unableToFork_parameter	decode_IMISC_IA5List
#define	free_IMISC_unableToFork_parameter	free_IMISC_IA5List
#else
#define	decode_IMISC_unableToFork_parameter	NULLIFP
#define	free_IMISC_unableToFork_parameter	NULLIFP
#endif

#ifdef	PERFORMER
#define	encode_IMISC_unableToFork_parameter	encode_IMISC_IA5List
#else
#define	encode_IMISC_unableToFork_parameter	NULLIFP
#endif


					/* ERROR errorReading */
#define error_IMISC_errorReading	6

#ifdef	INVOKER
#define	decode_IMISC_errorReading_parameter	decode_IMISC_IA5List
#define	free_IMISC_errorReading_parameter	free_IMISC_IA5List
#else
#define	decode_IMISC_errorReading_parameter	NULLIFP
#define	free_IMISC_errorReading_parameter	NULLIFP
#endif

#ifdef	PERFORMER
#define	encode_IMISC_errorReading_parameter	encode_IMISC_IA5List
#else
#define	encode_IMISC_errorReading_parameter	NULLIFP
#endif


					/* ERROR userNotLoggedIn */
#define error_IMISC_userNotLoggedIn	7

#ifdef	INVOKER
#define	decode_IMISC_userNotLoggedIn_parameter	NULLIFP
#define	free_IMISC_userNotLoggedIn_parameter	NULLIFP
#else
#define	decode_IMISC_userNotLoggedIn_parameter	NULLIFP
#define	free_IMISC_userNotLoggedIn_parameter	NULLIFP
#endif

#ifdef	PERFORMER
#define	encode_IMISC_userNotLoggedIn_parameter	NULLIFP
#else
#define	encode_IMISC_userNotLoggedIn_parameter	NULLIFP
#endif


