/* automatically generated by posy 7.0 #14 (nanook.mcc.com), do not edit! */

#ifndef	_module_IMISC_defined_
#define	_module_IMISC_defined_

#ifndef	PEPYPATH
#include <isode/psap.h>
#include <isode/pepy/UNIV-types.h>
#else
#include "psap.h"
#include "../pepy/UNIV-types.h"
#endif



#define	type_IMISC_UTCResult	type_UNIV_UniversalTime
#define	free_IMISC_UTCResult	free_UNIV_UniversalTime

#define	type_IMISC_GenResult	type_UNIV_GeneralizedTime
#define	free_IMISC_GenResult	free_UNIV_GeneralizedTime

#define	type_IMISC_Data	PElement
#define	free_IMISC_Data	pe_free

struct type_IMISC_IA5List {
        struct type_UNIV_IA5String *IA5String;

        struct type_IMISC_IA5List *next;
};
int	free_IMISC_IA5List ();

struct type_IMISC_TimeResult {
    integer    parm;
};
int	free_IMISC_TimeResult ();

struct type_IMISC_Empty {
    char    parm;
};
int	free_IMISC_Empty ();
#endif
