/* automatically generated by rosy 7.0 #14 (nanook.mcc.com), do not edit! */

#include <stdio.h>
#include "IMISC-ops.h"


#include "IMISC-types.h"

					/* OPERATIONS */

					/* OPERATION utcTime */
int	encode_IMISC_UTCResult (),
	decode_IMISC_UTCResult (),
	free_IMISC_UTCResult ();

static struct RyError *errors_IMISC_utcTime[] = {
    &table_IMISC_Errors[0],
    &table_IMISC_Errors[1]
};


					/* OPERATION timeOfDay */
int	encode_IMISC_TimeResult (),
	decode_IMISC_TimeResult (),
	free_IMISC_TimeResult ();

static struct RyError *errors_IMISC_timeOfDay[] = {
    &table_IMISC_Errors[0],
    &table_IMISC_Errors[1]
};


					/* OPERATION users */
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();

static struct RyError *errors_IMISC_users[] = {
    &table_IMISC_Errors[0],
    &table_IMISC_Errors[2]
};


					/* OPERATION charGen */
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();

static struct RyError *errors_IMISC_charGen[] = {
    &table_IMISC_Errors[0]
};


					/* OPERATION qotd */
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();

static struct RyError *errors_IMISC_qotd[] = {
    &table_IMISC_Errors[0],
    &table_IMISC_Errors[3],
    &table_IMISC_Errors[4],
    &table_IMISC_Errors[5],
    &table_IMISC_Errors[6]
};


					/* OPERATION finger */
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();

static struct RyError *errors_IMISC_finger[] = {
    &table_IMISC_Errors[0],
    &table_IMISC_Errors[3],
    &table_IMISC_Errors[4],
    &table_IMISC_Errors[5],
    &table_IMISC_Errors[6]
};


					/* OPERATION pwdGen */
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();

static struct RyError *errors_IMISC_pwdGen[] = {
    &table_IMISC_Errors[0]
};


					/* OPERATION genTime */
int	encode_IMISC_GenResult (),
	decode_IMISC_GenResult (),
	free_IMISC_GenResult ();

static struct RyError *errors_IMISC_genTime[] = {
    &table_IMISC_Errors[0],
    &table_IMISC_Errors[1]
};


					/* OPERATION tellUser */
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();
int	encode_IMISC_Empty (),
	decode_IMISC_Empty (),
	free_IMISC_Empty ();

static struct RyError *errors_IMISC_tellUser[] = {
    &table_IMISC_Errors[0],
    &table_IMISC_Errors[2],
    &table_IMISC_Errors[7]
};


					/* OPERATION ping */
int	encode_IMISC_Empty (),
	decode_IMISC_Empty (),
	free_IMISC_Empty ();
int	encode_IMISC_Empty (),
	decode_IMISC_Empty (),
	free_IMISC_Empty ();

static struct RyError *errors_IMISC_ping[] = {
    &table_IMISC_Errors[0]
};


					/* OPERATION sink */
int	encode_IMISC_Data (),
	decode_IMISC_Data (),
	free_IMISC_Data ();
int	encode_IMISC_Empty (),
	decode_IMISC_Empty (),
	free_IMISC_Empty ();

static struct RyError *errors_IMISC_sink[] = {
    &table_IMISC_Errors[0]
};


					/* OPERATION echo */
int	encode_IMISC_Data (),
	decode_IMISC_Data (),
	free_IMISC_Data ();
int	encode_IMISC_Data (),
	decode_IMISC_Data (),
	free_IMISC_Data ();

static struct RyError *errors_IMISC_echo[] = {
    &table_IMISC_Errors[0]
};


struct RyOperation table_IMISC_Operations[] = {
					/* OPERATION utcTime */
    "utcTime", operation_IMISC_utcTime,
	encode_IMISC_utcTime_argument,
 	decode_IMISC_utcTime_argument,
	free_IMISC_utcTime_argument,
	1, encode_IMISC_utcTime_result,
	   decode_IMISC_utcTime_result,
	   free_IMISC_utcTime_result,
	errors_IMISC_utcTime,

					/* OPERATION timeOfDay */
    "timeOfDay", operation_IMISC_timeOfDay,
	encode_IMISC_timeOfDay_argument,
 	decode_IMISC_timeOfDay_argument,
	free_IMISC_timeOfDay_argument,
	1, encode_IMISC_timeOfDay_result,
	   decode_IMISC_timeOfDay_result,
	   free_IMISC_timeOfDay_result,
	errors_IMISC_timeOfDay,

					/* OPERATION users */
    "users", operation_IMISC_users,
	encode_IMISC_users_argument,
 	decode_IMISC_users_argument,
	free_IMISC_users_argument,
	1, encode_IMISC_users_result,
	   decode_IMISC_users_result,
	   free_IMISC_users_result,
	errors_IMISC_users,

					/* OPERATION charGen */
    "charGen", operation_IMISC_charGen,
	encode_IMISC_charGen_argument,
 	decode_IMISC_charGen_argument,
	free_IMISC_charGen_argument,
	1, encode_IMISC_charGen_result,
	   decode_IMISC_charGen_result,
	   free_IMISC_charGen_result,
	errors_IMISC_charGen,

					/* OPERATION qotd */
    "qotd", operation_IMISC_qotd,
	encode_IMISC_qotd_argument,
 	decode_IMISC_qotd_argument,
	free_IMISC_qotd_argument,
	1, encode_IMISC_qotd_result,
	   decode_IMISC_qotd_result,
	   free_IMISC_qotd_result,
	errors_IMISC_qotd,

					/* OPERATION finger */
    "finger", operation_IMISC_finger,
	encode_IMISC_finger_argument,
 	decode_IMISC_finger_argument,
	free_IMISC_finger_argument,
	1, encode_IMISC_finger_result,
	   decode_IMISC_finger_result,
	   free_IMISC_finger_result,
	errors_IMISC_finger,

					/* OPERATION pwdGen */
    "pwdGen", operation_IMISC_pwdGen,
	encode_IMISC_pwdGen_argument,
 	decode_IMISC_pwdGen_argument,
	free_IMISC_pwdGen_argument,
	1, encode_IMISC_pwdGen_result,
	   decode_IMISC_pwdGen_result,
	   free_IMISC_pwdGen_result,
	errors_IMISC_pwdGen,

					/* OPERATION genTime */
    "genTime", operation_IMISC_genTime,
	encode_IMISC_genTime_argument,
 	decode_IMISC_genTime_argument,
	free_IMISC_genTime_argument,
	1, encode_IMISC_genTime_result,
	   decode_IMISC_genTime_result,
	   free_IMISC_genTime_result,
	errors_IMISC_genTime,

					/* OPERATION tellUser */
    "tellUser", operation_IMISC_tellUser,
	encode_IMISC_tellUser_argument,
 	decode_IMISC_tellUser_argument,
	free_IMISC_tellUser_argument,
	1, encode_IMISC_tellUser_result,
	   decode_IMISC_tellUser_result,
	   free_IMISC_tellUser_result,
	errors_IMISC_tellUser,

					/* OPERATION ping */
    "ping", operation_IMISC_ping,
	encode_IMISC_ping_argument,
 	decode_IMISC_ping_argument,
	free_IMISC_ping_argument,
	1, encode_IMISC_ping_result,
	   decode_IMISC_ping_result,
	   free_IMISC_ping_result,
	errors_IMISC_ping,

					/* OPERATION sink */
    "sink", operation_IMISC_sink,
	encode_IMISC_sink_argument,
 	decode_IMISC_sink_argument,
	free_IMISC_sink_argument,
	1, encode_IMISC_sink_result,
	   decode_IMISC_sink_result,
	   free_IMISC_sink_result,
	errors_IMISC_sink,

					/* OPERATION echo */
    "echo", operation_IMISC_echo,
	encode_IMISC_echo_argument,
 	decode_IMISC_echo_argument,
	free_IMISC_echo_argument,
	1, encode_IMISC_echo_result,
	   decode_IMISC_echo_result,
	   free_IMISC_echo_result,
	errors_IMISC_echo,

    NULL
};


					/* ERRORS */

int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();
int	encode_IMISC_IA5List (),
	decode_IMISC_IA5List (),
	free_IMISC_IA5List ();
struct RyError table_IMISC_Errors[] = {
					/* ERROR congested */
    "congested", error_IMISC_congested,
	encode_IMISC_congested_parameter,
	decode_IMISC_congested_parameter,
	free_IMISC_congested_parameter,

					/* ERROR unableToDetermineTime */
    "unableToDetermineTime", error_IMISC_unableToDetermineTime,
	encode_IMISC_unableToDetermineTime_parameter,
	decode_IMISC_unableToDetermineTime_parameter,
	free_IMISC_unableToDetermineTime_parameter,

					/* ERROR unableToOpenFile */
    "unableToOpenFile", error_IMISC_unableToOpenFile,
	encode_IMISC_unableToOpenFile_parameter,
	decode_IMISC_unableToOpenFile_parameter,
	free_IMISC_unableToOpenFile_parameter,

					/* ERROR unableToAccessFile */
    "unableToAccessFile", error_IMISC_unableToAccessFile,
	encode_IMISC_unableToAccessFile_parameter,
	decode_IMISC_unableToAccessFile_parameter,
	free_IMISC_unableToAccessFile_parameter,

					/* ERROR unableToPipe */
    "unableToPipe", error_IMISC_unableToPipe,
	encode_IMISC_unableToPipe_parameter,
	decode_IMISC_unableToPipe_parameter,
	free_IMISC_unableToPipe_parameter,

					/* ERROR unableToFork */
    "unableToFork", error_IMISC_unableToFork,
	encode_IMISC_unableToFork_parameter,
	decode_IMISC_unableToFork_parameter,
	free_IMISC_unableToFork_parameter,

					/* ERROR errorReading */
    "errorReading", error_IMISC_errorReading,
	encode_IMISC_errorReading_parameter,
	decode_IMISC_errorReading_parameter,
	free_IMISC_errorReading_parameter,

					/* ERROR userNotLoggedIn */
    "userNotLoggedIn", error_IMISC_userNotLoggedIn,
	encode_IMISC_userNotLoggedIn_parameter,
	decode_IMISC_userNotLoggedIn_parameter,
	free_IMISC_userNotLoggedIn_parameter,

    NULL
};
