0/16/2: IA5List |encode decode print
0/23/2: UTCResult |encode decode print
0/2/2: TimeResult |encode decode print
0/24/2: GenResult |encode decode print
-1/0/2: Data |encode decode print
0/5/2: Empty |encode decode print
0/16/1: IA5List |encode decode print
0/23/1: UTCResult |encode decode print
0/2/1: TimeResult |encode decode print
0/24/1: GenResult |encode decode print
-1/0/1: Data |encode decode print
0/5/1: Empty |encode decode print
