-- automatically generated by rosy 7.0 #14 (nanook.mcc.com), do not edit!

IMISC DEFINITIONS ::=

BEGIN

IA5List ::=
        SEQUENCE OF
            IA5String

UTCResult ::=
        UniversalTime

TimeResult ::=
        INTEGER

GenResult ::=
        GeneralizedTime

Data ::=
        ANY

Empty ::=
        NULL

END
