/* automatically generated by pepy 7.0 #14 (nanook.mcc.com), do not edit! */

#include "psap.h"

#define	advise	PY_advise

void	advise ();

/* Generated from module IMISC */

#include <stdio.h>
#include "IMISC-types.h"

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	encode_IMISC_GenResult (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
struct type_IMISC_GenResult * parm;
{
    if (encode_UNIV_GeneralizedTime (pe, 0, len, buffer, parm ) == NOTOK)
        return NOTOK;

#ifdef DEBUG
    (void) testdebug ((*pe), "IMISC.GenResult");
#endif


    return OK;
}
