package rholang.parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public class ENewPrompt extends Expr {
  public ENewPrompt() { }

  public <R,A> R accept(rholang.parsing.delimc.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.delimc.Absyn.ENewPrompt) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
