package rholang.parsing.delimc.Absyn; // Java Package generated by the BNF Converter.

public class ETuple extends Expr {
  public final Tuple tuple_;
  public ETuple(Tuple p1) { tuple_ = p1; }

  public <R,A> R accept(rholang.parsing.delimc.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.delimc.Absyn.ETuple) {
      rholang.parsing.delimc.Absyn.ETuple x = (rholang.parsing.delimc.Absyn.ETuple)o;
      return this.tuple_.equals(x.tuple_);
    }
    return false;
  }

  public int hashCode() {
    return this.tuple_.hashCode();
  }


}
