#!/bin/bash
set -eo pipefail

if [[ -n $DRONE_TAG ]]; then
	REF=$DRONE_TAG
	TAG=1
elif [[ -n $DRONE_BRANCH ]]; then
	REF=$DRONE_BRANCH
	if [[ $DRONE_BRANCH = "staging" ]]; then
	  # Staging is a branch used by bors for building pull requests before merging.
	  # All artifacts produced in those builds should be uploaded as if they were built on the PR's base/target branch.
	  COMMIT_MSG=$( git log -1 --pretty=format:%s )
	  PR_NUMBER=$( echo "$COMMIT_MSG" | sed -r 's/^Merge #([0-9]+).*$/\1/' )
	  REF=$( curl -s https://api.github.com/repos/rchain/rchain/pulls/$PR_NUMBER | jq -r '.base.ref' )
	fi
	TAG=0
else
	# Like, really. It'll overwrite your SSH key.
	echo "This script doesn't work outside of Drone" >&2
	exit 1
fi

# Upload packages to repo.pyr8.io

(
umask 077
mkdir -p ~/.ssh
echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' >~/.ssh/id_rsa
)

# We don't check host keys because artifacts are public.
rsync -avrz --delete -e "ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
    artifacts/*.deb artifacts/*.rpm artifacts/*.tgz \
    inbound@build.rchain-dev.tk:/srv/inbound/$REF/

# Upload Docker image

set +x
builtin echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

# There's a slight race condition between tag and push. Tag is fast, but what
# can happen if some other jobs tags with latest while push is in progress?

set -x

docker tag coop.rchain/rnode:DRONE-$DRONE_BUILD_NUMBER rchain/rnode:$REF
docker push rchain/rnode:$REF

if [[ $TAG == 1 ]]; then
	docker tag coop.rchain/rnode:DRONE-$DRONE_BUILD_NUMBER rchain/rnode:latest
	docker push rchain/rnode:latest
fi
