version: '3.1'

volumes:
    prometheus_data_storage: {}
    grafana_data_storage: {}
    rnode_data_storage: {}

services:
  prometheus-pushgateway:
    image: prom/pushgateway
    network_mode: "host"
  prometheus-server:
    image: prom/prometheus:v2.3.2
    network_mode: "host"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  grafana-ui:
    image: grafana/grafana:5.2.1
    network_mode: "host"
    env_file:
      - ./grafana/grafana.conf
    volumes:
      - grafana_data_storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
  zipkin:
    image: openzipkin/zipkin
    network_mode: "host"
