package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class Choice extends CBranch {
  public final ListBind listbind_;
  public final Expr expr_;
  public Choice(ListBind p1, Expr p2) { listbind_ = p1; expr_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.CBranch.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.Choice) {
      rholang.parsing.rholang1.Absyn.Choice x = (rholang.parsing.rholang1.Absyn.Choice)o;
      return this.listbind_.equals(x.listbind_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listbind_.hashCode())+this.expr_.hashCode();
  }


}
