package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class EConstr extends Expr {
  public final String name_;
  public final ListExpr listexpr_;
  public EConstr(String p1, ListExpr p2) { name_ = p1; listexpr_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.EConstr) {
      rholang.parsing.rholang1.Absyn.EConstr x = (rholang.parsing.rholang1.Absyn.EConstr)o;
      return this.name_.equals(x.name_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.name_.hashCode())+this.listexpr_.hashCode();
  }


}
