package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class EMatch extends Expr {
  public final Expr expr_;
  public final ListPMBranch listpmbranch_;
  public EMatch(Expr p1, ListPMBranch p2) { expr_ = p1; listpmbranch_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.EMatch) {
      rholang.parsing.rholang1.Absyn.EMatch x = (rholang.parsing.rholang1.Absyn.EMatch)o;
      return this.expr_.equals(x.expr_) && this.listpmbranch_.equals(x.listpmbranch_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.listpmbranch_.hashCode();
  }


}
