package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class ENew extends Expr {
  public final ListVar listvar_;
  public final Expr expr_;
  public ENew(ListVar p1, Expr p2) { listvar_ = p1; expr_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.ENew) {
      rholang.parsing.rholang1.Absyn.ENew x = (rholang.parsing.rholang1.Absyn.ENew)o;
      return this.listvar_.equals(x.listvar_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listvar_.hashCode())+this.expr_.hashCode();
  }


}
