package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public abstract class Entity implements java.io.Serializable {
  public abstract <R,A> R accept(Entity.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rholang.parsing.rholang1.Absyn.EChar p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.EStruct p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.ECollect p, A arg);

  }

}
