package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class EQuote extends Expr {
  public final Expr expr_;
  public EQuote(Expr p1) { expr_ = p1; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.EQuote) {
      rholang.parsing.rholang1.Absyn.EQuote x = (rholang.parsing.rholang1.Absyn.EQuote)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
