package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class EValue extends Expr {
  public final Value value_;
  public EValue(Value p1) { value_ = p1; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.EValue) {
      rholang.parsing.rholang1.Absyn.EValue x = (rholang.parsing.rholang1.Absyn.EValue)o;
      return this.value_.equals(x.value_);
    }
    return false;
  }

  public int hashCode() {
    return this.value_.hashCode();
  }


}
