package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public abstract class Pattern implements java.io.Serializable {
  public abstract <R,A> R accept(Pattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rholang.parsing.rholang1.Absyn.PtNil p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtVar p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtVal p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtDrop p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtInject p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtQuote p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtOutput p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtInput p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtMatch p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtNew p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtConstr p, A arg);
    public R visit(rholang.parsing.rholang1.Absyn.PtPar p, A arg);

  }

}
