package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class PtBind extends PatternBind {
  public final Pattern pattern_1, pattern_2;
  public PtBind(Pattern p1, Pattern p2) { pattern_1 = p1; pattern_2 = p2; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.PatternBind.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.PtBind) {
      rholang.parsing.rholang1.Absyn.PtBind x = (rholang.parsing.rholang1.Absyn.PtBind)o;
      return this.pattern_1.equals(x.pattern_1) && this.pattern_2.equals(x.pattern_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pattern_1.hashCode())+this.pattern_2.hashCode();
  }


}
