package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class PtConstr extends Pattern {
  public final String name_;
  public final ListPattern listpattern_;
  public PtConstr(String p1, ListPattern p2) { name_ = p1; listpattern_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.PtConstr) {
      rholang.parsing.rholang1.Absyn.PtConstr x = (rholang.parsing.rholang1.Absyn.PtConstr)o;
      return this.name_.equals(x.name_) && this.listpattern_.equals(x.listpattern_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.name_.hashCode())+this.listpattern_.hashCode();
  }


}
