package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class PtInput extends Pattern {
  public final ListPatternBind listpatternbind_;
  public final Pattern pattern_;
  public PtInput(ListPatternBind p1, Pattern p2) { listpatternbind_ = p1; pattern_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.PtInput) {
      rholang.parsing.rholang1.Absyn.PtInput x = (rholang.parsing.rholang1.Absyn.PtInput)o;
      return this.listpatternbind_.equals(x.listpatternbind_) && this.pattern_.equals(x.pattern_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listpatternbind_.hashCode())+this.pattern_.hashCode();
  }


}
