package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class PtMatch extends Pattern {
  public final Pattern pattern_;
  public final ListPatternPatternMatch listpatternpatternmatch_;
  public PtMatch(Pattern p1, ListPatternPatternMatch p2) { pattern_ = p1; listpatternpatternmatch_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.PtMatch) {
      rholang.parsing.rholang1.Absyn.PtMatch x = (rholang.parsing.rholang1.Absyn.PtMatch)o;
      return this.pattern_.equals(x.pattern_) && this.listpatternpatternmatch_.equals(x.listpatternpatternmatch_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pattern_.hashCode())+this.listpatternpatternmatch_.hashCode();
  }


}
