package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class PtVar extends Pattern {
  public final VarPattern varpattern_;
  public PtVar(VarPattern p1) { varpattern_ = p1; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.PtVar) {
      rholang.parsing.rholang1.Absyn.PtVar x = (rholang.parsing.rholang1.Absyn.PtVar)o;
      return this.varpattern_.equals(x.varpattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.varpattern_.hashCode();
  }


}
