package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public class QDouble extends Quantity {
  public final Double double_;
  public QDouble(Double p1) { double_ = p1; }

  public <R,A> R accept(rholang.parsing.rholang1.Absyn.Quantity.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang1.Absyn.QDouble) {
      rholang.parsing.rholang1.Absyn.QDouble x = (rholang.parsing.rholang1.Absyn.QDouble)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
