package rholang.parsing.rholang1.Absyn; // Java Package generated by the BNF Converter.

public abstract class ValPattern implements java.io.Serializable {
  public abstract <R,A> R accept(ValPattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rholang.parsing.rholang1.Absyn.VPtStruct p, A arg);

  }

}
