/* automatically generated by pepy 7.0 #14 (nanook.mcc.com), do not edit! */

#include "psap.h"

#define	advise	ryr_advise

void	advise ();

/* Generated from module PasswordLookup */

#include <stdio.h>
#include "PasswordLookup-types.h"

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;
# line 172 "PasswordLookup-types.py"


free_PasswordLookup_Passwd (arg)
struct type_PasswordLookup_Passwd *arg;
{
    struct type_PasswordLookup_Passwd *parm = arg;

    if (parm == NULL)
	return;

    if (parm -> name)
        free_PasswordLookup_UserName (parm -> name),
            parm -> name = NULL;
    if (parm -> passwd)
        free_UNIV_IA5String (parm -> passwd),
            parm -> passwd = NULL;
    if (parm -> uid)
        free_PasswordLookup_UserID (parm -> uid),
            parm -> uid = NULL;
    if (parm -> gid)
        free_PasswordLookup_GroupID (parm -> gid),
            parm -> gid = NULL;
    if (parm -> comment)
        free_UNIV_IA5String (parm -> comment),
            parm -> comment = NULL;
    if (parm -> gecos)
        free_UNIV_IA5String (parm -> gecos),
            parm -> gecos = NULL;
    if (parm -> dir)
        free_UNIV_IA5String (parm -> dir),
            parm -> dir = NULL;
    if (parm -> shell)
        free_UNIV_IA5String (parm -> shell),
            parm -> shell = NULL;

    free ((char *) arg);
}

free_PasswordLookup_UserID (arg)
struct type_PasswordLookup_UserID *arg;
{
    struct type_PasswordLookup_UserID *parm = arg;

    if (parm == NULL)
	return;


    free ((char *) arg);
}

free_PasswordLookup_GroupID (arg)
struct type_PasswordLookup_GroupID *arg;
{
    struct type_PasswordLookup_GroupID *parm = arg;

    if (parm == NULL)
	return;


    free ((char *) arg);
}

