/* automatically generated by pepy 7.0 #14 (nanook.mcc.com), do not edit! */

#include "psap.h"

#define	advise	ryr_advise

void	advise ();

/* Generated from module PasswordLookup */

#include <stdio.h>
#include "PasswordLookup-types.h"

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	encode_PasswordLookup_UserID (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
struct type_PasswordLookup_UserID * parm;
{
    register integer p2 = parm -> parm ;

    if (((*pe) = num2prim (p2, PE_CLASS_APPL, 3)) == NULLPE) {
        advise (NULLCP, "UserID: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "PasswordLookup.UserID");
#endif


    return OK;
}
