/* automatically generated by pepy 7.0 #14 (nanook.mcc.com), do not edit! */

#include "psap.h"

#define	advise	ryr_advise

void	advise ();

/* Generated from module PasswordLookup */

#include <stdio.h>
#include "PasswordLookup-types.h"

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	decode_PasswordLookup_UserID (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
struct type_PasswordLookup_UserID ** parm;
{
    register integer p15;

#ifdef DEBUG
    (void) testdebug (pe, "PasswordLookup.UserID");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_APPL, 3)) {
        advise (NULLCP, "UserID %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    {
# line 147 "PasswordLookup-types.py"

        if ((*(parm) = (struct type_PasswordLookup_UserID *)
                calloc (1, sizeof **(parm))) == ((struct type_PasswordLookup_UserID *) 0)) {
            advise (NULLCP, "%s", PEPY_ERR_NOMEM);
            return NOTOK;
        }
    
    }
    if ((p15 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "UserID %s%s", PEPY_ERR_BAD_INTEGER,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    (*parm) -> parm  = p15;
    if (len)
        *len = p15;

    return OK;
}
