/* automatically generated by pepy 7.0 #14 (nanook.mcc.com), do not edit! */

#include "psap.h"

#define	advise	ryr_advise

void	advise ();

/* Generated from module PasswordLookup */

#include <stdio.h>
#include "PasswordLookup-types.h"

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	encode_PasswordLookup_Passwd (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
struct type_PasswordLookup_Passwd * parm;
{
    PE	p0_z = NULLPE;
    register PE *p0 = &p0_z;

    if (((*pe) = pe_alloc (PE_CLASS_APPL, PE_FORM_CONS, 1)) == NULLPE) {
        advise (NULLCP, "Passwd: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }
    {
# line 20 "PasswordLookup-types.py"

            
    }
    (*p0) = NULLPE;

    {	/* name */
        if (encode_PasswordLookup_UserName (p0, 0, NULL, NULLCP, parm -> name ) == NOTOK)
            return NOTOK;
        (*p0) -> pe_class = PE_CLASS_CONT;
        (*p0) -> pe_id = 0;

#ifdef DEBUG
        (void) testdebug ((*p0), "name");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Passwd %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if (parm -> passwd) {	/* passwd */
        if (encode_UNIV_IA5String (p0, 0, NULL, NULLCP, parm -> passwd ) == NOTOK)
            return NOTOK;
        (*p0) -> pe_class = PE_CLASS_CONT;
        (*p0) -> pe_id = 1;

#ifdef DEBUG
        (void) testdebug ((*p0), "passwd");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Passwd %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    {	/* uid */
        if (encode_PasswordLookup_UserID (p0, 0, NULL, NULLCP, parm -> uid ) == NOTOK)
            return NOTOK;
        (*p0) -> pe_class = PE_CLASS_CONT;
        (*p0) -> pe_id = 2;

#ifdef DEBUG
        (void) testdebug ((*p0), "uid");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Passwd %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    {	/* gid */
        if (encode_PasswordLookup_GroupID (p0, 0, NULL, NULLCP, parm -> gid ) == NOTOK)
            return NOTOK;
        (*p0) -> pe_class = PE_CLASS_CONT;
        (*p0) -> pe_id = 3;

#ifdef DEBUG
        (void) testdebug ((*p0), "gid");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Passwd %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if (parm -> quota != 0) {	/* quota */
        register integer p1 = parm -> quota ;

        if (((*p0) = num2prim (p1, PE_CLASS_CONT, 4)) == NULLPE) {
            advise (NULLCP, "quota: %s", PEPY_ERR_NOMEM);
            return NOTOK;
        }

#ifdef DEBUG
        (void) testdebug ((*p0), "quota");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Passwd %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if (parm -> comment) {	/* comment */
        if (encode_UNIV_IA5String (p0, 0, NULL, NULLCP, parm -> comment ) == NOTOK)
            return NOTOK;
        (*p0) -> pe_class = PE_CLASS_CONT;
        (*p0) -> pe_id = 5;

#ifdef DEBUG
        (void) testdebug ((*p0), "comment");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Passwd %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if (parm -> gecos) {	/* gecos */
        if (encode_UNIV_IA5String (p0, 0, NULL, NULLCP, parm -> gecos ) == NOTOK)
            return NOTOK;
        (*p0) -> pe_class = PE_CLASS_CONT;
        (*p0) -> pe_id = 6;

#ifdef DEBUG
        (void) testdebug ((*p0), "gecos");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Passwd %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if (parm -> dir) {	/* dir */
        if (encode_UNIV_IA5String (p0, 0, NULL, NULLCP, parm -> dir ) == NOTOK)
            return NOTOK;
        (*p0) -> pe_class = PE_CLASS_CONT;
        (*p0) -> pe_id = 7;

#ifdef DEBUG
        (void) testdebug ((*p0), "dir");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Passwd %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if (parm -> shell) {	/* shell */
        if (encode_UNIV_IA5String (p0, 0, NULL, NULLCP, parm -> shell ) == NOTOK)
            return NOTOK;
        (*p0) -> pe_class = PE_CLASS_CONT;
        (*p0) -> pe_id = 8;

#ifdef DEBUG
        (void) testdebug ((*p0), "shell");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Passwd %s%s", PEPY_ERR_BAD_SEQ,
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "PasswordLookup.Passwd");
#endif


    return OK;
}
