/* automatically generated by rosy 7.0 #14 (nanook.mcc.com), do not edit! */

#include <stdio.h>
#include "PasswordLookup-ops.h"
#include "PasswordLookup-types.h"


#ifdef	lint

int	stub_PasswordLookup_lookupUser (sd, id, in, rfx, efx, class, roi)
int	sd,
	id,
	class;
struct type_PasswordLookup_UserName* in;
IFP	rfx,
	efx;
struct RoSAPindication *roi;
{
    return RyStub (sd, table_PasswordLookup_Operations, operation_PasswordLookup_lookupUser, id, NULLIP,
		(caddr_t) in, rfx, efx, class, roi);
}

int	op_PasswordLookup_lookupUser (sd, in, out, rsp, roi)
int	sd;
struct type_PasswordLookup_UserName* in;
caddr_t *out;
int    *rsp;
struct RoSAPindication *roi;
{
    return RyOperation (sd, table_PasswordLookup_Operations, operation_PasswordLookup_lookupUser,
		(caddr_t) in, out, rsp, roi);
}

int	stub_PasswordLookup_lookupUID (sd, id, in, rfx, efx, class, roi)
int	sd,
	id,
	class;
struct type_PasswordLookup_UserID* in;
IFP	rfx,
	efx;
struct RoSAPindication *roi;
{
    return RyStub (sd, table_PasswordLookup_Operations, operation_PasswordLookup_lookupUID, id, NULLIP,
		(caddr_t) in, rfx, efx, class, roi);
}

int	op_PasswordLookup_lookupUID (sd, in, out, rsp, roi)
int	sd;
struct type_PasswordLookup_UserID* in;
caddr_t *out;
int    *rsp;
struct RoSAPindication *roi;
{
    return RyOperation (sd, table_PasswordLookup_Operations, operation_PasswordLookup_lookupUID,
		(caddr_t) in, out, rsp, roi);
}
#endif
