/* automatically generated by rosy 7.0 #14 (nanook.mcc.com), do not edit! */

#include "rosy.h"


					/* OPERATIONS */

extern struct RyOperation table_PasswordLookup_Operations[];

					/* OPERATION lookupUser */
#define operation_PasswordLookup_lookupUser	0

#ifdef	INVOKER
#define	encode_PasswordLookup_lookupUser_argument	encode_PasswordLookup_UserName
#define	decode_PasswordLookup_lookupUser_result	decode_PasswordLookup_Passwd
#define	free_PasswordLookup_lookupUser_result	free_PasswordLookup_Passwd
#else
#define	encode_PasswordLookup_lookupUser_argument	NULLIFP
#define	decode_PasswordLookup_lookupUser_result	NULLIFP
#define	free_PasswordLookup_lookupUser_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_PasswordLookup_lookupUser_argument	decode_PasswordLookup_UserName
#define	free_PasswordLookup_lookupUser_argument	free_PasswordLookup_UserName
#define	encode_PasswordLookup_lookupUser_result	encode_PasswordLookup_Passwd
#else
#define	decode_PasswordLookup_lookupUser_argument	NULLIFP
#define	free_PasswordLookup_lookupUser_argument	NULLIFP
#define	encode_PasswordLookup_lookupUser_result	NULLIFP
#endif

					/* OPERATION lookupUID */
#define operation_PasswordLookup_lookupUID	1

#ifdef	INVOKER
#define	encode_PasswordLookup_lookupUID_argument	encode_PasswordLookup_UserID
#define	decode_PasswordLookup_lookupUID_result	decode_PasswordLookup_Passwd
#define	free_PasswordLookup_lookupUID_result	free_PasswordLookup_Passwd
#else
#define	encode_PasswordLookup_lookupUID_argument	NULLIFP
#define	decode_PasswordLookup_lookupUID_result	NULLIFP
#define	free_PasswordLookup_lookupUID_result	NULLIFP
#endif

#ifdef	PERFORMER
#define	decode_PasswordLookup_lookupUID_argument	decode_PasswordLookup_UserID
#define	free_PasswordLookup_lookupUID_argument	free_PasswordLookup_UserID
#define	encode_PasswordLookup_lookupUID_result	encode_PasswordLookup_Passwd
#else
#define	decode_PasswordLookup_lookupUID_argument	NULLIFP
#define	free_PasswordLookup_lookupUID_argument	NULLIFP
#define	encode_PasswordLookup_lookupUID_result	NULLIFP
#endif


#ifndef	lint

#define stub_PasswordLookup_lookupUser(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_PasswordLookup_Operations, operation_PasswordLookup_lookupUser, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_PasswordLookup_lookupUser(sd,in,out,rsp,roi)\
RyOperation ((sd), table_PasswordLookup_Operations, operation_PasswordLookup_lookupUser,\
	(caddr_t) (in), (out), (rsp), (roi))

#define stub_PasswordLookup_lookupUID(sd,id,in,rfx,efx,class,roi)\
RyStub ((sd), table_PasswordLookup_Operations, operation_PasswordLookup_lookupUID, (id), NULLIP,\
	(caddr_t) (in), (rfx), (efx), (class), (roi))

#define op_PasswordLookup_lookupUID(sd,in,out,rsp,roi)\
RyOperation ((sd), table_PasswordLookup_Operations, operation_PasswordLookup_lookupUID,\
	(caddr_t) (in), (out), (rsp), (roi))
#endif


					/* ERRORS */

extern struct RyError table_PasswordLookup_Errors[];

					/* ERROR noSuchUser */
#define error_PasswordLookup_noSuchUser	0

#ifdef	INVOKER
#define	decode_PasswordLookup_noSuchUser_parameter	NULLIFP
#define	free_PasswordLookup_noSuchUser_parameter	NULLIFP
#else
#define	decode_PasswordLookup_noSuchUser_parameter	NULLIFP
#define	free_PasswordLookup_noSuchUser_parameter	NULLIFP
#endif

#ifdef	PERFORMER
#define	encode_PasswordLookup_noSuchUser_parameter	NULLIFP
#else
#define	encode_PasswordLookup_noSuchUser_parameter	NULLIFP
#endif


					/* ERROR congested */
#define error_PasswordLookup_congested	1

#ifdef	INVOKER
#define	decode_PasswordLookup_congested_parameter	NULLIFP
#define	free_PasswordLookup_congested_parameter	NULLIFP
#else
#define	decode_PasswordLookup_congested_parameter	NULLIFP
#define	free_PasswordLookup_congested_parameter	NULLIFP
#endif

#ifdef	PERFORMER
#define	encode_PasswordLookup_congested_parameter	NULLIFP
#else
#define	encode_PasswordLookup_congested_parameter	NULLIFP
#endif


