package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class Choice extends CBranch {
  public final ListBind listbind_;
  public final Proc proc_;
  public Choice(ListBind p1, Proc p2) { listbind_ = p1; proc_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.CBranch.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.Choice) {
      rholang.parsing.rholang2.Absyn.Choice x = (rholang.parsing.rholang2.Absyn.Choice)o;
      return this.listbind_.equals(x.listbind_) && this.proc_.equals(x.proc_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listbind_.hashCode())+this.proc_.hashCode();
  }


}
