package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public abstract class Contr implements java.io.Serializable {
  public abstract <R,A> R accept(Contr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rholang.parsing.rholang2.Absyn.DContr p, A arg);

  }

}
