package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public abstract class CPattern implements java.io.Serializable {
  public abstract <R,A> R accept(CPattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rholang.parsing.rholang2.Absyn.CPtVar p, A arg);
    public R visit(rholang.parsing.rholang2.Absyn.CPtQuote p, A arg);

  }

}
