package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class CPtQuote extends CPattern {
  public final PPattern ppattern_;
  public CPtQuote(PPattern p1) { ppattern_ = p1; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.CPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.CPtQuote) {
      rholang.parsing.rholang2.Absyn.CPtQuote x = (rholang.parsing.rholang2.Absyn.CPtQuote)o;
      return this.ppattern_.equals(x.ppattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.ppattern_.hashCode();
  }


}
