package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class InputBind extends Bind {
  public final CPattern cpattern_;
  public final Chan chan_;
  public InputBind(CPattern p1, Chan p2) { cpattern_ = p1; chan_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.Bind.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.InputBind) {
      rholang.parsing.rholang2.Absyn.InputBind x = (rholang.parsing.rholang2.Absyn.InputBind)o;
      return this.cpattern_.equals(x.cpattern_) && this.chan_.equals(x.chan_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.cpattern_.hashCode())+this.chan_.hashCode();
  }


}
