package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class PatternMatch extends PMBranch {
  public final PPattern ppattern_;
  public final Proc proc_;
  public PatternMatch(PPattern p1, Proc p2) { ppattern_ = p1; proc_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.PMBranch.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.PatternMatch) {
      rholang.parsing.rholang2.Absyn.PatternMatch x = (rholang.parsing.rholang2.Absyn.PatternMatch)o;
      return this.ppattern_.equals(x.ppattern_) && this.proc_.equals(x.proc_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ppattern_.hashCode())+this.proc_.hashCode();
  }


}
