package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public abstract class PatternBind implements java.io.Serializable {
  public abstract <R,A> R accept(PatternBind.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rholang.parsing.rholang2.Absyn.PtBind p, A arg);

  }

}
