package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class PDrop extends Proc {
  public final Chan chan_;
  public PDrop(Chan p1) { chan_ = p1; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.Proc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.PDrop) {
      rholang.parsing.rholang2.Absyn.PDrop x = (rholang.parsing.rholang2.Absyn.PDrop)o;
      return this.chan_.equals(x.chan_);
    }
    return false;
  }

  public int hashCode() {
    return this.chan_.hashCode();
  }


}
