package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class PLift extends Proc {
  public final Chan chan_;
  public final ListProc listproc_;
  public PLift(Chan p1, ListProc p2) { chan_ = p1; listproc_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.Proc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.PLift) {
      rholang.parsing.rholang2.Absyn.PLift x = (rholang.parsing.rholang2.Absyn.PLift)o;
      return this.chan_.equals(x.chan_) && this.listproc_.equals(x.listproc_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.chan_.hashCode())+this.listproc_.hashCode();
  }


}
