package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class PNil extends Proc {
  public PNil() { }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.Proc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.PNil) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
