package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class PPtConstr extends PPattern {
  public final String name_;
  public final ListPPattern listppattern_;
  public PPtConstr(String p1, ListPPattern p2) { name_ = p1; listppattern_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.PPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.PPtConstr) {
      rholang.parsing.rholang2.Absyn.PPtConstr x = (rholang.parsing.rholang2.Absyn.PPtConstr)o;
      return this.name_.equals(x.name_) && this.listppattern_.equals(x.listppattern_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.name_.hashCode())+this.listppattern_.hashCode();
  }


}
