package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class PPtInput extends PPattern {
  public final ListPatternBind listpatternbind_;
  public final PPattern ppattern_;
  public PPtInput(ListPatternBind p1, PPattern p2) { listpatternbind_ = p1; ppattern_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.PPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.PPtInput) {
      rholang.parsing.rholang2.Absyn.PPtInput x = (rholang.parsing.rholang2.Absyn.PPtInput)o;
      return this.listpatternbind_.equals(x.listpatternbind_) && this.ppattern_.equals(x.ppattern_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listpatternbind_.hashCode())+this.ppattern_.hashCode();
  }


}
