package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class PPtMatch extends PPattern {
  public final PPattern ppattern_;
  public final ListPatternPatternMatch listpatternpatternmatch_;
  public PPtMatch(PPattern p1, ListPatternPatternMatch p2) { ppattern_ = p1; listpatternpatternmatch_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.PPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.PPtMatch) {
      rholang.parsing.rholang2.Absyn.PPtMatch x = (rholang.parsing.rholang2.Absyn.PPtMatch)o;
      return this.ppattern_.equals(x.ppattern_) && this.listpatternpatternmatch_.equals(x.listpatternpatternmatch_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ppattern_.hashCode())+this.listpatternpatternmatch_.hashCode();
  }


}
