package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class PVar extends Proc {
  public final String var_;
  public PVar(String p1) { var_ = p1; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.Proc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.PVar) {
      rholang.parsing.rholang2.Absyn.PVar x = (rholang.parsing.rholang2.Absyn.PVar)o;
      return this.var_.equals(x.var_);
    }
    return false;
  }

  public int hashCode() {
    return this.var_.hashCode();
  }


}
