package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class QInt extends Quantity {
  public final Integer integer_;
  public QInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.Quantity.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.QInt) {
      rholang.parsing.rholang2.Absyn.QInt x = (rholang.parsing.rholang2.Absyn.QInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
