package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public abstract class Quantity implements java.io.Serializable {
  public abstract <R,A> R accept(Quantity.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rholang.parsing.rholang2.Absyn.QInt p, A arg);
    public R visit(rholang.parsing.rholang2.Absyn.QDouble p, A arg);

  }

}
