package rholang.parsing.rholang2.Absyn; // Java Package generated by the BNF Converter.

public class StructConstr extends Struct {
  public final String var_;
  public final ListProc listproc_;
  public StructConstr(String p1, ListProc p2) { var_ = p1; listproc_ = p2; }

  public <R,A> R accept(rholang.parsing.rholang2.Absyn.Struct.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rholang.parsing.rholang2.Absyn.StructConstr) {
      rholang.parsing.rholang2.Absyn.StructConstr x = (rholang.parsing.rholang2.Absyn.StructConstr)o;
      return this.var_.equals(x.var_) && this.listproc_.equals(x.listproc_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.var_.hashCode())+this.listproc_.hashCode();
  }


}
