#!/bin/bash
set -eu -o pipefail

source ./virtualenv_init

export DEFAULT_IMAGE=rchain-integration-tests:latest
docker build -t $DEFAULT_IMAGE .

# TEMP_RESOURCES_DIR is going to be removed after tests finish if and only if
# it was not given to us from the environment (i.e. we're going to create new
# one) and all tests finish successfully.

cleanup=0

if [[ ! -v TEMP_RESOURCES_DIR ]]; then
	TEMP_RESOURCES_DIR=$(mktemp --tmpdir -d integration-tests.XXXXXXXXXX)
	cleanup=1
fi

echo "Using temporary directory $TEMP_RESOURCES_DIR"

ret=0
TMPDIR=$TEMP_RESOURCES_DIR python3 -m pytest -v "$@" || ret=$?

if (( ret == 0 && cleanup == 1 )); then
	echo "Removing temporary directory $TEMP_RESOURCES_DIR"
	rm -rf "$TEMP_RESOURCES_DIR"
fi

exit $ret
