{
 "title": "RNode Counter Metrics(All)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "rspace_comm_produce_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rspace_comm_produce_total" }
   ]
  },
  {
   "title": "block_store_put_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "block_store_put_total" }
   ]
  },
  {
   "title": "tracer_spans_created_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tracer_spans_created_total" }
   ]
  },
  {
   "title": "block_store_as_map_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "block_store_as_map_total" }
   ]
  },
  {
   "title": "replayrspace_comm_produce_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "replayrspace_comm_produce_total"
    }
   ]
  },
  {
   "title": "mempool_ps_eden_space_peak_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_ps_eden_space_peak_commited"
    }
   ]
  },
  {
   "title": "mempool_ps_old_gen_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_old_gen_commited" }
   ]
  },
  {
   "title": "memory_non_heap_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "memory_non_heap_used" }
   ]
  },
  {
   "title": "memory_heap_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "memory_heap_max" }
   ]
  },
  {
   "title": "mempool_compressed_class_space_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_compressed_class_space_commited"
    }
   ]
  },
  {
   "title": "size{path=\"/var/lib/rnode/rspace/casper\"}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "size{path=\"/var/lib/rnode/rspace/casper\"}"
    }
   ]
  },
  {
   "title": "size{path=\"/var/lib/rnode/rspace\"}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "size{path=\"/var/lib/rnode/rspace\"}"
    }
   ]
  },
  {
   "title": "thread_total_started",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "thread_total_started" }
   ]
  },
  {
   "title": "mempool_code_cache_peak_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_code_cache_peak_max" }
   ]
  },
  {
   "title": "mempool_ps_old_gen_peak_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_ps_old_gen_peak_commited"
    }
   ]
  },
  {
   "title": "mempool_code_cache_peak_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_code_cache_peak_commited"
    }
   ]
  },
  {
   "title": "mempool_metaspace_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_metaspace_init" }
   ]
  },
  {
   "title": "mempool_metaspace_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_metaspace_commited" }
   ]
  },
  {
   "title": "mempool_code_cache_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_code_cache_commited" }
   ]
  },
  {
   "title": "mempool_compressed_class_space_peak_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_compressed_class_space_peak_used"
    }
   ]
  },
  {
   "title": "mempool_compressed_class_space_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_compressed_class_space_init"
    }
   ]
  },
  {
   "title": "thread_count_daemon",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "thread_count_daemon" }
   ]
  },
  {
   "title": "gc_ps_scavenge_total_collections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gc_ps_scavenge_total_collections"
    }
   ]
  },
  {
   "title": "thread_count_peak",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "thread_count_peak" }
   ]
  },
  {
   "title": "mempool_ps_eden_space_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_eden_space_commited" }
   ]
  },
  {
   "title": "mempool_ps_old_gen_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_old_gen_used" }
   ]
  },
  {
   "title": "gc_ps_scavenge_total_collection_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gc_ps_scavenge_total_collection_time"
    }
   ]
  },
  {
   "title": "gc_ps_marksweep_duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gc_ps_marksweep_duration" }
   ]
  },
  {
   "title": "mempool_metaspace_peak_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_metaspace_peak_init" }
   ]
  },
  {
   "title": "mempool_ps_survivor_space_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_survivor_space_used" }
   ]
  },
  {
   "title": "memory_heap_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "memory_heap_commited" }
   ]
  },
  {
   "title": "memory_heap_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "memory_heap_used" }
   ]
  },
  {
   "title": "mempool_ps_survivor_space_peak_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_ps_survivor_space_peak_max"
    }
   ]
  },
  {
   "title": "gc_ps_scavenge_end_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gc_ps_scavenge_end_time" }
   ]
  },
  {
   "title": "mempool_code_cache_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_code_cache_init" }
   ]
  },
  {
   "title": "process_cpu_load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_load" }
   ]
  },
  {
   "title": "mempool_compressed_class_space_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_compressed_class_space_max"
    }
   ]
  },
  {
   "title": "memory_non_heap_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "memory_non_heap_init" }
   ]
  },
  {
   "title": "mempool_code_cache_peak_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_code_cache_peak_init" }
   ]
  },
  {
   "title": "mempool_code_cache_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_code_cache_max" }
   ]
  },
  {
   "title": "entries{path=\"/var/lib/rnode/rspace/casper\"}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "entries{path=\"/var/lib/rnode/rspace/casper\"}"
    }
   ]
  },
  {
   "title": "entries{path=\"/var/lib/rnode/rspace\"}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "entries{path=\"/var/lib/rnode/rspace\"}"
    }
   ]
  },
  {
   "title": "mempool_metaspace_peak_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_metaspace_peak_max" }
   ]
  },
  {
   "title": "mempool_ps_old_gen_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_old_gen_init" }
   ]
  },
  {
   "title": "mempool_ps_survivor_space_peak_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_ps_survivor_space_peak_used"
    }
   ]
  },
  {
   "title": "gc_ps_marksweep_total_collections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gc_ps_marksweep_total_collections"
    }
   ]
  },
  {
   "title": "gc_ps_scavenge_duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gc_ps_scavenge_duration" }
   ]
  },
  {
   "title": "mempool_ps_old_gen_peak_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_old_gen_peak_used" }
   ]
  },
  {
   "title": "mempool_metaspace_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_metaspace_used" }
   ]
  },
  {
   "title": "mempool_ps_eden_space_peak_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_ps_eden_space_peak_used"
    }
   ]
  },
  {
   "title": "mempool_ps_old_gen_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_old_gen_max" }
   ]
  },
  {
   "title": "thread_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "thread_count" }
   ]
  },
  {
   "title": "mempool_metaspace_peak_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_metaspace_peak_commited"
    }
   ]
  },
  {
   "title": "mempool_ps_survivor_space_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_ps_survivor_space_commited"
    }
   ]
  },
  {
   "title": "memory_non_heap_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "memory_non_heap_max" }
   ]
  },
  {
   "title": "mempool_compressed_class_space_peak_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_compressed_class_space_peak_commited"
    }
   ]
  },
  {
   "title": "mempool_metaspace_peak_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_metaspace_peak_used" }
   ]
  },
  {
   "title": "mempool_ps_survivor_space_peak_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_ps_survivor_space_peak_commited"
    }
   ]
  },
  {
   "title": "mempool_ps_eden_space_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_eden_space_max" }
   ]
  },
  {
   "title": "gc_ps_scavenge_start_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gc_ps_scavenge_start_time" }
   ]
  },
  {
   "title": "mempool_ps_survivor_space_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_survivor_space_max" }
   ]
  },
  {
   "title": "gc_ps_marksweep_start_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gc_ps_marksweep_start_time" }
   ]
  },
  {
   "title": "mempool_compressed_class_space_peak_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_compressed_class_space_peak_init"
    }
   ]
  },
  {
   "title": "mempool_ps_survivor_space_peak_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_ps_survivor_space_peak_init"
    }
   ]
  },
  {
   "title": "mempool_metaspace_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_metaspace_max" }
   ]
  },
  {
   "title": "mempool_ps_old_gen_peak_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_old_gen_peak_max" }
   ]
  },
  {
   "title": "memory_non_heap_commited",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "memory_non_heap_commited" }
   ]
  },
  {
   "title": "mempool_ps_old_gen_peak_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_old_gen_peak_init" }
   ]
  },
  {
   "title": "mempool_ps_eden_space_peak_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_eden_space_peak_max" }
   ]
  },
  {
   "title": "mempool_code_cache_peak_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_code_cache_peak_used" }
   ]
  },
  {
   "title": "mempool_compressed_class_space_peak_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_compressed_class_space_peak_max"
    }
   ]
  },
  {
   "title": "gc_ps_marksweep_end_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gc_ps_marksweep_end_time" }
   ]
  },
  {
   "title": "mempool_compressed_class_space_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_compressed_class_space_used"
    }
   ]
  },
  {
   "title": "process_cpu_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_time" }
   ]
  },
  {
   "title": "mempool_ps_eden_space_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_eden_space_init" }
   ]
  },
  {
   "title": "memory_heap_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "memory_heap_init" }
   ]
  },
  {
   "title": "mempool_ps_survivor_space_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_survivor_space_init" }
   ]
  },
  {
   "title": "mempool_ps_eden_space_peak_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_ps_eden_space_peak_init"
    }
   ]
  },
  {
   "title": "gc_ps_marksweep_total_collection_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gc_ps_marksweep_total_collection_time"
    }
   ]
  },
  {
   "title": "mempool_code_cache_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_code_cache_used" }
   ]
  },
  {
   "title": "mempool_ps_eden_space_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mempool_ps_eden_space_used" }
   ]
  }
 ]
}